name: Obfucc-LLVM CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: 15
          env: true

      - name: Add LLVM to PATH (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "$env:LLVM_PATH\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Add LLVM to PATH (Unix)
        if: runner.os != 'Windows'
        run: echo "$LLVM_PATH/bin" >> "$GITHUB_PATH"

      - name: Build tiny test obfucc (Unix)
        if: runner.os != 'Windows'
        run: python3 tests/runner.py --build-only
        shell: bash

      - name: Build tiny test obfucc (Windows)
        if: runner.os == 'Windows'
        run: python tests/runner.py --build-only
        shell: pwsh

      - name: Run smoke tests (Unix)
        if: runner.os != 'Windows'
        run: bash tests/run_smoke.sh
        shell: bash

      - name: Run smoke tests (Windows)
        if: runner.os == 'Windows'
        run: pwsh -File tests/run_smoke.ps1
        shell: pwsh

      - name: Run regression tests (Unix)
        if: runner.os != 'Windows'
        run: bash tests/run_regressions.sh
        shell: bash

      - name: Run regression tests (Windows)
        if: runner.os == 'Windows'
        run: pwsh -File tests/run_regressions.ps1
        shell: pwsh

  build-only:
    name: Build-only on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: 15
          env: true

      - name: Add LLVM to PATH (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "$env:LLVM_PATH\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Add LLVM to PATH (Unix)
        if: runner.os != 'Windows'
        run: echo "$LLVM_PATH/bin" >> "$GITHUB_PATH"

      - name: Run build-only harness (Unix)
        if: runner.os != 'Windows'
        run: python3 tests/runner.py --build-only
        shell: bash

      - name: Run build-only harness (Windows)
        if: runner.os == 'Windows'
        run: python tests/runner.py --build-only
        shell: pwsh
